### ISSUE TITLE
[🐛버그] 모달창을 닫을 경우 메인 페이지로 이동하는 버그 발생

### ISSUE THREAD

**Issue by kimzeze** [likelion-lab15/essentia#39]
## 문제 설명

![모달창 오류](https://github.com/likelion-lab15/essentia/assets/96248861/75804dba-13aa-4023-b8a0-0a5984028074)

### 상황설명
- 카카오 우편번호 검색 API를 사용하여 모달창 컴포넌트를 만들었습니다.
- 회원가입 페이지에서 주소검색 버튼을 누르면 모달형식으로 보이도록 작성했습니다.
-> 위 상황에서 주소검색을 하지 않고 close 버튼을 눌렀을 때 회원가입 페이지를 벗어나는 버그가 발생하였습니다.

### AddressModal.tsx
<img width="874" alt="image" src="https://github.com/likelion-lab15/essentia/assets/96248861/f94f20aa-751b-4eb6-a91b-e52de049d64e">

### Singup.tsx
<img width="729" alt="image" src="https://github.com/likelion-lab15/essentia/assets/96248861/567bf7f7-b9d1-4e38-b211-b0482e951ec3">

## 해결 방법

<img width="668" alt="image" src="https://github.com/likelion-lab15/essentia/assets/96248861/229c5634-93f8-4936-be0d-3be0b254164f">

문제 원인은 form 태그에 action='/' 속성이 지정되어 있어 모달창을 닫으면서 홈으로 이동하는 버그가 발생한 것 같습니다.
어떠한 이유에선지 form 태그가 제출한 것으로 인식하는 것 같아 action 속성을 제거하고 event.preventDefault()를 호출하여 기본 폼 제출 동작을 방지했습니다.

## 추가 코멘트
회원가입 버튼을 눌렀을 때 정상적으로 서버에 form 태그의 값들이 들어가는지 확인해야합니다.

**Comment by rlawlsdn263** [comment]
💯

**Comment by hyunzsu** [comment]
💯
