### ISSUE TITLE
[🐛Bug] Axios를 사용하여 에러 핸들링시 타입 에러가 발생합니다

### ISSUE THREAD

**Issue by kimzeze** [likelion-lab15/essentia#55]
## 버그 설명
<img width="828" alt="image" src="https://github.com/likelion-lab15/essentia/assets/96248861/35836c76-be69-4cd2-8763-8715d49da036">
<img width="679" alt="image" src="https://github.com/likelion-lab15/essentia/assets/96248861/e62da794-b386-4994-a45e-500b7f6c9ed8">

- 위 코드는 이메일 중복확인을 하기 위한 Axios Get 통신을 사용하는 코드입니다.
- `409 에러`가 발생하면 중복된 이메일이라는 뜻이기 때문에 409에러가 반환되면 사용자에게 오류메세지를 전송하도록 설계하였습니다.
- 하지만 error 속성에 접근할 경우 `error`는 `unknown`형식이라는 경고 메세지가 발생합니다.

## 해결 방법

아직 해결하지 못했습니다

## 추가 코멘트

Axios를 사용하면서 이와 같은 에러를 해결했다면 공유해주세요

## 이슈 트래커

Ref: #18

**Comment by rlawlsdn263** [comment]
타입스크립트 에러로 보이는데 기능 구현에도 현재 지장이 있나요?

**Comment by kimzeze** [comment]
> 타입스크립트 에러로 보이는데 기능 구현에도 현재 지장이 있나요?

기능에는 문제가 없습니다. 검색해보니 타입가드를 권장하는데 결국 any 타입을 사용해야 해결되는 것 같아서 이슈로 등록해두었습니다 ~!!

**Comment by rlawlsdn263** [comment]
> > > 타입스크립트 에러로 보이는데 기능 구현에도 현재 지장이 있나요?
> > 
> > 
> > 기능에는 문제가 없습니다. 검색해보니 타입가드를 권장하는데 결국 any 타입을 사용해야 해결되는 것 같아서 이슈로 등록해두었습니다 ~!!
> 
> 알겠습니다~ 혹시라도 any 타입보다 더 나은 방향을 알게된다면 저도 공유해보도록 하겠습니다

`instanceof` 타입 가드를 통해 해결하는 방법을 알아냈습니다.  `error.response`로 인해 발생하는 타입스크립트 에러는 `Error` 인스턴스에 `response` 속성이 없기 때문에 발생하는 걸로 보입니다.

ref: #100
